[theme]
base = "dark"
primaryColor = "#67A2FF"
backgroundColor = "#182338"
secondaryBackgroundColor = "#24334F"
textColor = "#F2F6FF"
borderColor = "#415575"
showWidgetBorder = true
baseRadius = "medium"
